project:
  type: website
  output-dir: docs

website:
  title: "Meu site - Gleison Soares Veras"
  navbar:
    left:
      - href: dashboard.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

css: styles.css


